version: "2"

services:

  web:
    build: .
    image: k1nz_checker_web2
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - FLAG=flag{fake_flag}
