version: '3.8'
services:
  server:
    container_name: rce_me
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:80
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped